//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace ProductManagementSystem.Models.PMSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Customers = new HashSet<Customer>();
        }
    
        public int Id { get; set; }
        [DisplayName("Product Code")]
        [Required(ErrorMessage = "Field is required")]
        public string ProductCode { get; set; }
        [DisplayName("Product Name")]
        public string ProductName { get; set; }
        [DisplayName("Product Description")]
        public string ProductDesc { get; set; }
        public Nullable<int> OwnerId { get; set; }
        [DisplayName("Created Date")]
        public System.DateTime CreatedDate { get; set; }
        [DisplayName("Valid Till")]
        public System.DateTime ValidTill { get; set; }
        [DisplayName("Price")]
        public Nullable<int> Price { get; set; }
        [DisplayName("Quantity")]
        public int Quantity { get; set; }
    
        public virtual Owner Owner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer> Customers { get; set; }
    }
}
